baseURL: "https://mariochvx.com"
languageCode: "en-us"
title: "Mario Chávez"
theme: hugo-profile

# Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 2

    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2

# Dropdown menu
    - identifier: about
      title: 
      name: About me
      weight: 3
    - identifier: about1
      title: Introduction
      name: Introduction
      url: /#about
      parent: about
      weight: 1
    - identifier: about2
      title: Experience
      name: Experience
      url: /#experience
      parent: about
      weight: 1
    - identifier: about3
      title: Education
      name: Education
      url: /#education
      parent: about
      weight: 1
    - identifier: about4
      title: Projects
      name: Projects
      url: /#Projects
      parent: about
      weight: 1

params:
  title: "MarioChvx"
  description: Personal site where I talk about my professional history and interests, also about my hobbies.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/2.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: true

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" #"light"  dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  navbar:
    align: me-auto
    disableSearch: true
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
  #     disableContact: true

# Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Mario."
    subtitle: "Data scientist"
    content: |- 
      I am interested in data science, machine learning, deep learning and Linux operative systems.
    image: /images/avatar.jpg
    button:
      enable: true
      name: "Resume"
      url: "/files/mario-chavez-resume.pdf"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/MarioChvx
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/mariochvx/
        - icon: fab fa-whatsapp
          url: https://wa.me/5215515359878
        - icon: fas fa-envelope
          url: mailto:mariochavez1292@gmail.com
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

# About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am a Data scientist. I have a strong interest in big bata, machine learning, deep learning, and Unix operative systems. Outside Software Development world. I also enjoy PC hardware, calisthenics, and cooking.

      I am currently looking for work, open to learn new skills, developing personal projects with the technologies I like.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "PostgreSQL"
        - "GCP"
        - "Linux"
        - "Bash"
        - "MarkDown"

# Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "First Line Specialist"
        company: "Tecnostaff (Banorte)"
        date: "2018 - 2018"
        content: |-
          **Technical Support**
          - At first my duty was trying to restore the function of the blocked ATMs by sending remote commands if that didn't work I've to coordinated appointments for the maintenance and repair of ATMs.

          **Data Base Administrator**
          - Later, due to my knowledge in databases, my role changed to manage the database where the issues were recorded and I developed some scripts to optimize the CRUD process and performance reporting.

# Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Technical Skills"
        school: 
          name: "Platzi"
          url: "https://platzi.com/home"
        date: "Present"
        content: "Online educational platform, where I learn new technologies and keep myself updated in other technologies, taking the courses available there."

      - title: "Bachelor in Data Science"
        school:
          name: "Escuela Superior de Computo, IPN"
          url: "https://www.escom.ipn.mx/"
        date: "2021 - present"
        content: |-
           Extracurricular Activities
            - I was a volunteer tutor teaching topics such as Python programing, C programing, Calculus etc.

      - title: "Bachelor of Engineering in Bionics"
        school:
          name: "Unidad Profesional Interdisciplinaria en Ingeniería y Tecnologías Avanzadas, IPN"
          url: "https://www.upiita.ipn.mx/"
        date: "2019 - 2021"
        content: |-
          Extracurricular Activities
            - I was a volunteer tutor teaching topics such as Python programing, C programing, Calculus etc.
            - Also I was one of the responsible for the calisthenics club.

# projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: OTP ETL
        content: A ETL script to store historical data about some players from League of Legends game.
        image: /images/projects/sionornn.jpg
        featured:
          name: Source Code
          link: https://github.com/MarioChvx/otp_etl.git
        badges:
          - "Python"
          - "PostgreSQL"
          - "API"
        links:
          - icon: fab fa-github
            url: https://github.com/MarioChvx/otp_etl.git
      - title: Console Manga Downloader
        content: A command line console to download manga from various websites, with just a little bit of information.
        image: /images/projects/keyboardmanga.png
        featured:
          name: Source Code
          link: https://github.com/MarioChvx/cli_manga_downloader
        badges:
          - "Python"
          - "BS4"
        links:
          - icon: fab fa-github
            url: https://github.com/MarioChvx/console_manga_downloader.git

# Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Winner of Physics Statal Contest
        content: Annual physics contest organized by the government. It consist on three fazes of eliminatory exams and then the winner is selected.
        # url: https://example.com

  #Contact
  contact:
    enable: true
    title: "Contact me"
    content: If you want to collaborate with me, discuss or chat about my site, give me a tip or anything.
    email: mariochavez1292@gmail.com
    btnName: mariochavez1292@gmail.com

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/MarioChvx
      linkedin: https://linkedin.com/in/mariochvx/
